### ISSUE TITLE
hyp3-autorift assumes S2 scenes names longer than 24 char are ESA names

### ISSUE THREAD

**Issue by jhkennedy** [ASFHyP3/hyp3-autorift#152]
Similar to ASFHyP3/hyp3#1022

`hyp3_autorfit.process.get_datetime`
https://github.com/ASFHyP3/hyp3-autorift/blob/develop/hyp3_autorift/process.py#L145-L146

will assume any Sentinel-2 scene with a name longer than 24 characters is a Sentinel-2 ESA name, not a COG name. But, there are valid 25 character COG names. 

This *may not* be the only place this assumption exists (but I *think* it is).

**Comment by forrestfwilliams** [comment]
I've submitted PR #154 to fix this issue. I couldn't find anywhere else where this issue comes up other than the line you mentioned.
