### ISSUE TITLE
If the autoRIFT input image projections are different, reproject to the reference scene crs

### ISSUE THREAD

**Issue by jhkennedy** [ASFHyP3/hyp3-autorift#186]
This is likely only needed for the Landsat mission.

Projection info should be in the metadata. 

- [x] confirm parameter files are based on the reference scene
- [x] #187
- [ ] #188

**Comment by asjohnston0** [comment]
this is a test

**Comment by shubhayanroychowdhury** [comment]
![Image](https://user-images.githubusercontent.com/129718401/229470325-e9a2e7b7-7689-4ebc-9682-36097588528d.png)
![Image](https://user-images.githubusercontent.com/129718401/229470326-64c8ea95-f612-4f87-bbef-d17bab4e8784.png)
