### ISSUE TITLE
S2 names should use COG Identifier

### ISSUE THREAD

**Issue by Jlrine2** [ASFHyP3/hyp3-autorift#30]
S2 names are currently given using the ESA identifier (e.g. `S2B_MSIL2A_20200903T151809_N0214_R068_T22WEB_20200903T194353`), we should change to the COG identifier (e.g. `S2B_22WEB_20200903_0_L2A`) because that's what Mark's pair list uses.

Also, consider validation of granule names and pairs here:

- both are valid names
- both are from the same mission

**Comment by jhkennedy** [comment]
Done in #33
