### ISSUE TITLE
grid spacing not being read from parameter files

### ISSUE THREAD

**Issue by alex-s-gardner** [ASFHyP3/hyp3-autorift#68]
**bug**
I'm pointing autoRIFT to the new shapefile that in-turn points to the 120m gridded parameter files but they are producing 240m grids... tracing the issue a bit it looks like it must happen on the gdal call to retrieve the parameters.
For example the parameter file: http://its-live-data.jpl.nasa.gov.s3.amazonaws.com/autorift_parameters/v001/SPS_0120m_yMinChipSize.tif
has a 120 m grid spacing but the file "SPS_0120m_yMinChipSize.tif" created by the autoRIFT workflow has 240m grid spacing 

****
this line: https://github.com/ASFHyP3/hyp3-autorift/blob/develop/hyp3_autorift/io.py#L86

hyp3_autorift/io.py:86
            out_path, tif, outputBounds=output_bounds, xRes=240, yRes=240, targetAlignedPixels=True, multithread=True,

needs to get xRes and yRes from the input file 

** ALSO MAKE SURE THAT PIXELS CENTERS ARE NOT BEING MOVED FROM ORIGINAL PARAMETER FILE **

**Comment by jhkennedy** [comment]
Fixed in #80, closing.
